### ISSUE TITLE
i can t run the predict model and download the model

### ISSUE THREAD

**Issue by dobbleheart** [matlab-deep-learning/Text-Detection-using-Deep-Learning#1]

**Comment by anshika-MW** [comment]
Hi @dobbleheart 
Sorry for the delay in response.

It is my understanding that you are not able to download the model and hence, predict is not working.

I hope you have run the [setup](https://github.com/matlab-deep-learning/Text-Detection-using-Deep-Learning#setup) command.
On my end, everything is working properly. Can you share the snippet of error (if any) or the script you are using?

**Comment by dobbleheart** [comment]
There is a zip in the project.there are some mistake ,can you give me some advice on it ?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "matlab-deep-learning/Text-Detection-using-Deep-Learning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月6日(星期四) 下午4:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [matlab-deep-learning/Text-Detection-using-Deep-Learning] i can t run the predict model and download the model (Issue #1)





 
Hi @dobbleheart
 Sorry for the delay in response.
 
It is my understanding that you are not able to download the model and hence, predict is not working.
 
I hope you have run the setup command.
 On my end, everything is working properly. Can you share the snippet of error (if any) or the script you are using?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by anshika-MW** [comment]
@dobbleheart 
Are you referring to craftModel.zip file? Can you elaborate your issue or share some snippet of your issue?

**Comment by anshika-MW** [comment]
Closing the issue as there is no response.
