### ISSUE TITLE
hello sir, why the final layer is not a output layer ?

### ISSUE THREAD

**Issue by StarDxxx** [matlab-deep-learning/Text-Detection-using-Deep-Learning#2]
I want to use craftNet to train my data, so i use 
`lgraph = layerGraph(craftNet);`,
but i find this lgraph is not a correct laygraph beacuse it does not have a output layer.

![craftNet](https://user-images.githubusercontent.com/36352922/152319374-1a650bad-f70d-4dce-9b10-ea168baa74a9.PNG)
![outputlayers](https://user-images.githubusercontent.com/36352922/152319384-7d218161-68d6-4500-bf45-b3f4ca63bcf3.PNG)

so, when i use this code
`
lgraph = layerGraph(craftNet); 
net = trainNetwork(Xtrain,YTrain,lgraph,options);
`
he told me that my lgraph don have a output layer, so I can't train my network.

And i also find that, i can't import dlnetwork type object to deep learning network design app, just can import layers, or others.

Thanks for your help！

**Comment by StarDxxx** [comment]
sorry, Mrs. Anshika

**Comment by anshika-MW** [comment]
Hello @StarDxxx 
It is my understanding that you wanted to train 'craftNet' on your dataset. 

Following resources you can refer to train dlnetwork using custom training loop:

- https://in.mathworks.com/help/deeplearning/ug/train-network-using-custom-training-loop.html
- https://github.com/matlab-deep-learning/pretrained-efficientdet-d0/blob/main/efficientDetD0TransferLearn.m
- https://github.com/matlab-deep-learning/pretrained-yolo-v4/blob/main/yolov4TransferLearn.m

Moreover, currently deep network designer doesn't support import of dlnetwork.

Hope it helps!

**Comment by StarDxxx** [comment]
Thank you very much!  @anshika-MW 
Now i can train my network correctly! thanks
